title: KorGE
email: soywiz@gmail.com
description: Modern Kotlin Common Libraries for Full Stack development
authors: soywiz and KorGE authors
analytics_id: G-KV32JER3MJ
exclude:
  - ".gradle"
  - ".idea"
  - ".sass-cache"
  - ".vscode"
  - "@old"
baseurl: ""
url: "https://www.korge.cn"
edit_root_url: https://github.com/jisoypub/korge.cn/blob/main/
blog_url: ""
project_url: https://github.com/jisoypub/korge.cn/
google_search_id: 001447907640164080602:ej0h0w0ufr0
github_username:  jisoypub
# DISQUS is super intrusive lately
#disqus_id: "korlibs-documentation"
markdown: kramdown
kramdown:
  syntax_highlighter_opts:
    disable : true
sass:
  sass_dir: css
plugins:
  #- jekyll-redirect-from
  #- hook-add-last-modified-date
  - jekyll-i18n
languages:
  - en
  - zh
default_language: en
